# Order Service - Production Configuration

name: order-service
namespace: orders

image:
  repository: ghcr.io/medhunk94/order-service
  tag: "feature-systemcharts"
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

healthCheck:
  livenessPath: /health
  readinessPath: /health
  initialDelaySeconds: 10
  periodSeconds: 10

config:
  KAFKA_BROKER: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_TOPIC: "order-topic"
  CONSUMER_GROUP: "order-processor-group"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
