apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: checkout-secrets
  namespace: checkout
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: checkout-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: checkout/database
        property: password
    - secretKey: kafka-password
      remoteRef:
        key: checkout/kafka
        property: password
