apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      allowPrivilegeEscalation controls whether a process can gain more privileges
      than its parent process. Even a non-root container can escalate privileges
      via setuid binaries if this is not explicitly disabled.
spec:
  validationFailureAction: {{ .Values.enforcementMode }}
  background: true
  rules:
    - name: disallow-privilege-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
              {{- range .Values.excludedNamespaces }}
                - {{ . }}
              {{- end }}
      validate:
        message: "Privilege escalation is not allowed. Set securityContext.allowPrivilegeEscalation: false"
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
